language: haskell
install:
  - ./sync-all -r https://github.com/ghc get
  - ./sync-all -r https://github.com/ghcjs --ghcjs get
  - ./sync-all checkout ghc-7.6
  - ./unpack.sh
  - cp mk/build.mk.sample mk/build.mk
  - cd libraries/ghcjs
  - git checkout gen2
  - cd ../..
script:
  - sh ghcjs-build.sh
notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
  email: true
