language: haskell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install darcs
  - sudo apt-get clean
install:
  - ./sync-all -r https://github.com/ghc get
  - ./sync-all -r https://github.com/ghcjs --ghcjs get
  - ./sync-all checkout ghc-7.6
  - ./unpack.sh
script:
  - sh -ex ghcjs-build.sh
notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
  email: true
